name: Run Playwright auto-checks
on:
  push:
    branches: ['main']
    paths-ignore:
      - '**/*.md'
jobs:
  playwright-api-auto-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18 
      - name: Docker image pull
        run: | 
          docker pull httpd
      - name: Build Docker image
        run: | 
         docker build -t cscentral .
      - name: Run http-server in Docker
        run: |
          docker run -d --name cscentral -p 127.0.0.1:8080:80 my-apache2
      - name: Change env variable from prod to local
        run: |
          echo "ci=true" >> .env
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Chromium Browser
        run: npx playwright install --with-deps chromium
      - name: Run auto-checks
        run: npx playwright test
      - name: Archive tests results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            ./playwright-report/**/*.*
            ./test-results/**/*.*
